apiVersion: v1
kind: Service
metadata:
  name: k8s-drupal-deploy-test
  namespace: dev
spec:
  selector:
    name: k8s-drupal-deploy-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer